---
kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node
    commands:
      - yarn install
      - yarn build

pipeline:
  netlify:
    image: lucap/drone-netlify
    token:
      from-secret: netlify_token
    site_id:
      from_secret: site_id
