---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: "gzip"
      mount:
        - "./node_modules"

    volumes:
      - name: cache
        path: /tmp/cache

  - name: frontend
    image: node
    commands:
      - yarn install
      - yarn build

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: "gzip"
      mount:
        - "./node_modules"
    volumes:
      - name: cache
        path: /tmp/cache

  - name: deploy
    image: node
    environment:
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_SITE_ID
    commands:
      - bash deploy.sh

volumes:
  - name: cache
    host:
      path: /var/lib/cache

